name: format fix

on:
  pull_request:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: format check
      uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    - run: |
       npm ci
       npm run format:check
