name: format check & lint check

on:
  pull_request:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: preparing
      uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    - run: |
       npm ci
       
    - name: format check
      run: npm run format:check
      
    - name: lint check
      run: npm run lint:check
      
