name: format fix

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:

    - name: ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_SECRET }}
        username: ${{ secrets.USSER_SECRET }}
        key: ${{ secrets.OMG_SECRET }}
        port: ${{ secrets.PORT }}
        
    - uses: actions/setup-node@v1
      with:
        node-version: 16.14.2   
    - name: npm install 
      run: |
        npm install
        npm run lint:check
          
          
          
          
