name: format fix

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:

    - name: ssh commands using password
    - uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_SECRET }}
        username: ${{ secrets.USSER_SECRET }}
        key: ${{ secrets.OMG_SECRET }}
        port: ${{ secrets.PORT }}
        script: |
          cd kyvechecker

    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '14'
    - run: |
        npm install
        npm ci
        npm -v
        node -v

          
          
          
          
